language: rust
env:
  global:
    - secure: XU8Jjl3q3lYiMog5dWsP4BHWyAl5uXKouiYDo6lW1m51byJV+oflLO+BEjkJT7e1RHylR2rLh6zGZfBiz9JCMX2si98Yvb5PahugkVNg61A86bhb0iu0fnevrJyS31rHOAtkOL5d3lnkTb3frGNKJSOrBs1dIU8h3XstoqU4uag=
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
