[package]

name = "skeletal_animation"
version = "0.1.0"
authors = ["stjahns <s.t.jahns@gmail.com>"]
keywords = ["animation", "character", "skeletal", "gfx"]
description = "Skeletal character animation library, using gfx-rs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/skeletal_animation"
homepage = "https://github.com/PistonDevelopers/skeletal_animation"

[lib]

name = "skeletal_animation"
path = "src/lib.rs"

[dependencies]

rustc-serialize = "*"
collada = "*"
vecmath = "*"
quaternion = "*"
dual_quaternion = "*"
gfx = "0.6.*"
piston-gfx_texture = "*"
interpolation = "*"
piston-float = "*"
gfx_debug_draw = "0.3.*"