[package]

name = "skeletal_animation"
version = "0.0.1"
authors = ["stjahns <s.t.jahns@gmail.com>"]

[dependencies]
rustc-serialize = "*"

[dependencies.collada]
git = "https://github.com/PistonDevelopers/piston_collada"

[dependencies.gfx_debug_draw]
git = "https://github.com/PistonDevelopers/gfx-debug-draw"

[dependencies.vecmath]
git = "https://github.com/PistonDevelopers/vecmath"

[dependencies.quaternion]
git = "https://github.com/PistonDevelopers/quaternion"

[dependencies.dual_quaternion]
git = "https://github.com/PistonDevelopers/dual_quaternion"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.gfx_macros]
git = "https://github.com/gfx-rs/gfx_macros"

[dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl"

[dependencies.piston-gfx_texture]
git = "https://github.com/pistondevelopers/gfx_texture.git"

[dependencies.interpolation]
git = "https://github.com/pistondevelopers/interpolation.git"
